spring.datasource.url=jdbc:mysql://localhost:3306/locavia?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.com.PiCloud.locavia=DEBUG
logging.level.org.springframework.security=DEBUG

application.url-frontend=http://localhost:4200
application.jwt.secret=4D6A514B53516F5134743777217A25432A462D4A614E645267556B5870327335
application.jwt.expiration=86400000

# ✅ nouvelle clé secrète v2
application.recaptcha.cle-secrete=6LcoFacsAAAAADzFs1dPQcEaF20R31JS1msNxnH9
application.recaptcha.url-verification=https://www.google.com/recaptcha/api/siteverify
application.google.client-id=131584557440-570e1vpovbrfiadsobqe0vbgti1qpb75.apps.googleusercontent.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=maram.rabeh7@gmail.com
spring.mail.password=xzjkwuxdoyfwnxne
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.default-encoding=UTF-8

# ✅ Twilio
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=c94748dee739f76444120272ade004a9
twilio.phone-number=+17407566798

# Sécurité
application.tentatives-max=3
application.blocage-secondes=30