# Spring Profiles
spring.profiles.active=prod
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/locavia?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto= none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:test@test.com}
spring.mail.password=${MAIL_PASSWORD:test}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Application Security & JWT
application.jwt.secret=${JWT_SECRET:4D6A514B53516F5134743777217A25432A462D4A614E645267556B5870327335}
application.jwt.expiration=86400000

# Recaptcha Configuration
application.recaptcha.cle-secrete=${RECAPTCHA_SECRET:6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI}
application.recaptcha.url-verification=https://www.google.com/recaptcha/api/siteverify

# Integration & Social
application.url-frontend=${FRONTEND_URL:http://localhost:4200}
application.google.client-id=${GOOGLE_CLIENT_ID:your-google-client-id}




pdf.keystore.path=classpath:locavia-keystore.p12
pdf.keystore.password=locavia2025
pdf.keystore.alias=locavia



# Google Meet

google.meet.base-url=https://meet.googleapis.com/v2

google.client.id=${GOOGLE_CLIENT_ID}
google.client.secret=${GOOGLE_CLIENT_SECRET}
google.refresh.token=${GOOGLE_REFRESH_TOKEN}


app.upload.video-dir=uploads/videos
app.base-url=http://localhost:8080
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

app.upload.visite3d-dir=uploads/visites3d

gemini.api.key=${GEMINI_API_KEY}
# Stripe Configuration (Ajoute ces 3 lignes pour être sûr)
stripe.api.key=${STRIPE_API_KEY}
stripe.secret.key=${STRIPE_API_KEY}
stripe.key=${STRIPE_API_KEY}